### ISSUE TITLE
Add a record: the last time the world was unloaded(high priority)

### ISSUE THREAD

**Issue by TWME-TW** [thomasmny/BuildSystem#184]
### What problem does this feature solve?

Let us know when the world was last loaded

Also add a placeholder %lastload% ?

**Comment by EinJOJO** [comment]
As far as I am aware, each world gets loaded when the server starts but it gets unloaded after a period of time.
I think it would be more interesting when a player was last in the world, which would also include your aspect of last loading because a player can only join a world if it is loaded.
Anyways I like the idea.

**Comment by TWME-TW** [comment]
Agreed, recording the last time the player left would be better.

**Comment by thomasmny** [comment]
> As far as I am aware, each world gets loaded when the server starts but it gets unloaded after a period of time.
> I think it would be more interesting when a player was last in the world, which would also include your aspect of last loading because a player can only join a world if it is loaded.
> Anyways I like the idea.

The worlds are only pre-loaded if `unload-worlds` in set to false. Otherwise the loading is skipped
https://github.com/thomasmny/BuildSystem/blob/bb68bd4bd633df6f7406efd82860dcb6206af259/buildsystem-core/src/main/java/com/eintosti/buildsystem/config/WorldConfig.java#L39
